- sdk/nodejs/__tests__/models/variable.spec.ts
- sdk/nodejs/src/models/variable.ts
- made node js sdk keys for variables lower case
> fix: lower case key for variables

- scripts/npm-safe-publish.sh
yarn 3 isn't happy about being running inside the dist/ directory packages.
switch to using `npm publish` for publishing
> chore: switch to npm for publishing

- sdk/nodejs/package.json
- sdk/nodejs/src/client.ts
- Set the minimum node version to 14, while we sort out issues with node versions < 14
- fix null exception
- mark async functions
> DVC-3088 set minimum node version to 14, add null checks

- lib/shared/bucketing-assembly-script/project.json
- scripts/npm-safe-publish.sh
fixing the `npm-safe-publish.sh` script to support how the bucketing-assembly-script package is setup, need to use a different `jq` search param to get proper npm version
> fixing npm-safe-publish.sh script 

- sdk/react/src/DVCProvider.tsx
- sdk/react/src/context.ts
- sdk/react/src/initializeDVCClient.ts
- sdk/react/src/useDVCClient.ts
- sdk/react/src/useVariable.ts
- `initializeDVCClient` returns the client object instead of a promise
- update context typing so the client is not undefined in `useDVCClient`: https://medium.com/@rivoltafilippo/typing-react-context-to-avoid-an-undefined-default-value-2c7c5a7d5947
> fix: change initializeDVCClient to return client instead of promise

- package.json
- yarn.lock
The most recent versions fixed the binding issue when using in NodeJS with a fetch polyfill.
> fix: update assemblyscript to fix bindings for bucketing code

- sdk/js/src/Client.ts
- sdk/js/src/Request.ts
- sdk/js/src/types.ts
- yarn.lock
- option added: `enableCloudData`
- note: backend setting will be called `enableCloudEntityData`
> Add SDK option to enable cloud data saving for user

- sdk/js/src/EventQueue.ts
- sdk/js/src/Request.ts
- sdk/js/src/RequestEvent.ts
- sdk/js/src/utils.ts
- allows `variableDefaulted` events and other custom tracked events to be flushed before the config is ready
- events are associated with `user_id` but have no `featureVars`
> fix: flush events before config is ready

- sdk/js/src/Client.ts
The identifyUser function was saving the old user to edgeDB, rather than the updated version which is, at this point in the code, only saved in the `updatedUser` variable
> save the updated user to edgedb

- lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
- lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
- lib/shared/bucketing-assembly-script/assembly/types/bucketedUserConfig.ts
- lib/shared/bucketing-assembly-script/assembly/types/feature.ts
- lib/shared/bucketing-test-data/src/data/testData.ts
- lib/shared/bucketing/__test__/bucketing.test.ts
- lib/shared/bucketing/src/bucketing.ts
- lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
- lib/shared/types/src/types/config/models/feature.ts
Final result is variationKey and variationName added to the features in the bucketed config (so getAllFeatures in SDKs will include those keys), and no changes made to variations in the bucketed config
We talked about adding feature name as well, but that requires a config service change as well so i'm going to get this merged first and then separate the name-related changes into their own commit / PR
> Dvc 3528 add variationKey to bucketed features and remove from variable 

- examples/react/with-provider/src/DevCycleExample.tsx
- lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
- lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
- package.json
- yarn.lock
- switch to our fork of the assemblyscript-json lib which removes all usages of template literals. These cause gc issues due to a bug in assemblyscript
https://github.com/AssemblyScript/assemblyscript/issues/2178
> fix: use forked assemblyscript json lib to resolve memory gc issue

- sdk/nodejs/__tests__/client.spec.ts
- sdk/nodejs/src/__mocks__/bucketing.ts
- sdk/nodejs/src/client.ts
- send `variableDefaulted` event only when variable is NOT in bucketed config
> [DVC-3403] variableDefaulted logging

- sdk/nodejs/__tests__/cloudClient.spec.ts
- sdk/nodejs/src/__mocks__/handlers.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/cloudClient.ts
- sdk/nodejs/src/request.ts
- sdk/nodejs/src/types.ts
- adds `enableEdgeDB` to DVCOptions
- checks is `enableEdgeDB` option is set to true && `enableCloudBucketing` is set to true, to pass through Enable EdgeDB to Bucketing API
- creates INFO level log, if `enableEdgeDB` is set to true without Cloud Bucketing
> Enable EdgeDB for NodeJS SDK

- lib/shared/types/src/types/config/models/project.ts
- sdk/nodejs/__tests__/eventQueue.spec.ts
- sdk/nodejs/src/eventQueue.ts
- added function to find equivalent event queue size for aggregate events and user events
- drops events and aggregate events from queueing if max event queue size limit is reached
- add type for future use of configurable event queue size from bucketed config
> feat: added a max event queue size for storing events

- sdk/nodejs/src/index.ts
- make enableCloudBucketing param optional
- default to false for NodeJS SDK to ensure local bucketing is the default functionality when the option isn't present
> NodeJS SDK: make enableCloudBucketing param optional & add default value

- lib/shared/bucketing/src/bucketing.ts
- lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
- lib/shared/types/src/types/config/models/feature.ts
- adds settings to SDK Feature on the User Config if it exists on the Project Config
- does not have the settings key if the `feature.settings.optInEnabled` is false
> Add Name, Description and Settings to SDK Feature

- lib/shared/types/.babelrc
- sdk/js/src/Client.ts
- mongo object Id is only available for the `variableEvaluated` events
> DVC-2495: add value, type, and _variable to event metadata

- package.json
- yarn.lock
Origin library makes assumptions about node-fetch versions that are more advanced than what is used in NextJS
> Use assemblyscript fork

- lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
- lib/shared/bucketing-assembly-script/__tests__/setPlatformData.ts
- lib/shared/bucketing-assembly-script/__tests__/types/platformData.test.ts
- lib/shared/bucketing-assembly-script/assembly/eventQueue/requestPayloadManager.ts
- lib/shared/bucketing-assembly-script/assembly/test.ts
- lib/shared/bucketing-assembly-script/assembly/types/platformData.ts
- sdk/nodejs/__tests__/client.spec.ts
- sdk/nodejs/src/client.ts
Pass in `hostname` as part of platformData, use for `user_id` of aggregated events.
> DVC-4286 hostname support

- examples/nodejs-local/js/src/main.js
- examples/nodejs-local/typescript/src/main.ts
- sdk/nodejs/__tests__/initialize.spec.ts
- sdk/nodejs/src/index.ts
- make `options` optional when calling `initialize` on the NodeJS SDK, this makes the NodeJS SDK startup in Local bucketing mode by default
- update NodeJS example apps
> Fix nodejs sdk startup without options

- lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
- lib/shared/bucketing-assembly-script/assembly/eventQueue/eventQueue.ts
- lib/shared/bucketing-assembly-script/assembly/eventQueue/requestPayloadManager.ts
- lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
- lib/shared/bucketing-assembly-script/assembly/types/eventQueueOptions.ts
- sdk/nodejs/__tests__/eventQueueAS.test.ts
- sdk/nodejs/src/eventQueueAS.ts
- sdk/nodejs/src/types.ts
- keep track of the number of queued events + events in payload objects
- implement param checking for eventQueue options
- keep track if a flush is in-progress
- trigger a flush on `flushEventQueueSize` param, start dropping events at `maxEventQueueSize` length.
> DVC-4285 implement max queue size

- sdk/nodejs/__tests__/clientCleanup.test.ts
- sdk/nodejs/__tests__/testCloseProcess.js
- sdk/nodejs/jest.config.ts
- sdk/nodejs/src/client.ts
- add a method called `close` which will clean up any open handles keeping the node process open
- add a test that fires off a child process and makes sure that it closes properly
> feat: add cleanup method to nodejs sdk to allow cleaning up of resources

- lib/shared/types/package.json
- yarn.lock
- add dependency on `@types/validator` to allow for proper production builds with the NodeJS SDK
- see source issue at https://github.com/nestjs/class-validator/issues/79
> add @types/validator as a dependency of @devcycle/types

- lib/shared/bucketing-test-data/project.json
- lib/shared/types/project.json
set `buildableProjectDepsInPackageJsonType` nx build option for all external packages.
> fix package peerDependancies

- sdk/js/__tests__/Client.spec.js
- sdk/js/__tests__/EventQueue.spec.js
- sdk/js/src/Client.ts
- sdk/js/src/EventQueue.ts
- sdk/js/src/types.ts
- add close method to clsoe active resources such as event flush interval and streaming connection
- wait for event flush to happen
- also prevent new events from being tracked after closing
> feat: add close method to JS SDK to close active resources

- sdk/js/src/Client.ts
- sdk/js/src/types.ts
- sdk/react/src/DVCProvider.tsx
- add proper unmount for react provider
- ensure provider only creates one client at a time and cleans itself up
> fix: react sdk properly unmounts and closes client

- scripts/npm-safe-publish.sh
- work around Nx bugs by moving the otp check to happen only when we're actually publishing the package
- publish will work as long as `nx affected` sees that all the packages need to be published, because it forwards the `otp` flag to each top-level task that is being executed
- however, if you just try to publish one package that happens to have dependencies which are already published, it will fail because Nx won't forward the `otp` flag to the dependent publish tasks
- these tasks won't do anything anyways since the versions are already published, so allow them to succeed without having the otp flag set by moving that check after the no-op publish check.
> chore: move otp check in publish script

- sdk/js/src/StreamingConnection.ts
- sdk/react/src/DVCProvider.tsx
- sdk/react/src/useVariable.ts
- fix react SDK not rerendering properly when variable value was changed
- optimize how the rerendering works so that it doesnt rerender the entire application tree when a variable changes`
> fix: react now rerenders properly on variable change

- sdk/js/__tests__/Client.spec.js
- sdk/js/src/EventEmitter.ts
- iterate over the unique set of variable keys to avoid double-calling onUpdate
> fix: js sdk now calls onUpdate once instead of twice

- lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
Currently the opt-on APIs are requiring the full user object when they should only require the user_id
This will be used by the /v1/optInConfig APIs
> Add DVCOptInUser type for opt-in APIs

- lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
Fix this error when `isolatedModules` is enabled in a project:
```
Type error: A type referenced in a decorated signature must be imported with 'import type' or a namespace import when 'isolatedModules' and 'emitDecoratorMetadata' are enabled.
```
> fix: import type properly

- sdk/js/src/Client.ts
Added if statement to future proof future messages by refetching only when type is `refetchConfig`, or if type is `undefined`.
> chore: adding extra logic to refetch when type is refetchConfig

- lib/shared/bucketing-assembly-script/index.js
- lib/shared/bucketing-assembly-script/project.json
- lib/shared/types/src/reporter.ts
- sdk/nodejs/src/bucketing.ts
- sdk/nodejs/src/client.ts
- report on WASM memory usage every 30 sec
- allow WebAssembly.MemoryDescriptor to be set as start option
- Change default initial WASM memory to 1,000 pages = 64 mb, max 10,000 pages = 640 mb
> TAP-8702 report WASM memory usage

- nx.json
Working around this Nx bug
https://github.com/nrwl/nx/issues/9317
> fix: specifying libs dir breaks next app builds in Nx

- examples/react/next-js-app/.eslintrc.json
- lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
- lib/shared/types/src/types/config/models/variable.ts
- lib/shared/types/src/types/validators/dvcJSON.ts
- package.json
- sdk/js/src/User.ts
- sdk/js/src/Variable.ts
- sdk/js/src/index.ts
- sdk/js/src/types.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/models/populatedUser.ts
- sdk/nodejs/src/models/variable.ts
- sdk/nodejs/src/types.ts
- sdk/react/__mocks__/@devcycle/devcycle-js-sdk.ts
- sdk/react/jest.config.ts
- sdk/react/src/useVariableValue.test.tsx
- sdk/react/src/useVariableValue.ts
- sdk/react/tsconfig.lib.json
- sdk/react/tsconfig.spec.json
- yarn.lock
- fix React type definition to work in example apps
- write tests for useVariableValue to test types
- rename `JSON` type to `DVCJSON` to prevent conflicts with global JSON
> fix: type definitions for example apps, write tests and change JSON type export

- sdk/js/__tests__/Client.spec.js
- sdk/js/src/Client.ts
- remove anonymous user id from local storage on reset
- branch out from and merge after https://github.com/DevCycleHQ/js-sdks/pull/323
> Dvc 5114 js sdk remove id from localstorage on reset

- .github/workflows/run-test-harness.yml
Fix workflow not being triggered for running test harness. Added logic to use `yarn nx print-affected` to only run test harness if `nodejs` is a project affected.
> fix: trigger test harness if nodejs files change

- sdk/js/src/CacheStore.ts
- sdk/js/src/Client.ts
- update checking to avoid falling to unreasonable reasons
- e.g. previous logic if no config, it falls to user id not match
> update skipping config cache checking

- .github/workflows/run-test-harness.yml
- regex wasnt matching properly when nodejs was the first entry on the list of `nx affected`
> fix: grep for test harness filtering

- lib/shared/types/src/utils.ts
- sdk/nodejs/__tests__/client.spec.ts
- sdk/nodejs/__tests__/cloudClient.spec.ts
- sdk/nodejs/__tests__/models/variable.spec.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/cloudClient.ts
- sdk/nodejs/src/models/variable.ts
- ensure type field is always set on DVCVariable instances in NodeJS
- field will be set to the type determined by the defaultValue passed to the variable call
> fix: nodejs should always set type field on variable instance

- sdk/js/__tests__/Client.spec.js
- sdk/js/src/Client.ts
reuses cached anonymous user id if no user_id is provided
> fix identify user  call on JS SDK for anonymous users

- sdk/nodejs/__tests__/environmentConfigManager.spec.ts
- sdk/nodejs/src/environmentConfigManager.ts
When a 403 is received (invalid sdk key), stop polling for configs
> fix: stop config polling when a 403 is received

- examples/nodejs-cloud/js/src/main.js
- examples/nodejs-cloud/typescript/src/main.ts
- examples/nodejs-local/js/src/main.js
- examples/nodejs-local/typescript/src/main.ts
- sdk/nodejs/__tests__/environmentConfigManager.spec.ts
- sdk/nodejs/__tests__/eventQueue.test.ts
- sdk/nodejs/__tests__/request.spec.ts
- sdk/nodejs/src/environmentConfigManager.ts
- sdk/nodejs/src/eventQueue.ts
- sdk/nodejs/src/index.ts
- sdk/nodejs/src/request.ts
- sdk/nodejs/src/utils/paramUtils.ts
- yarn.lock
- rename `envKey` / `token` to `sdkKey` in NodeJS SDK to improve consistency across our SDKs
> DVC-5923 rename envKey to sdkKey in NodeJS SDK

- lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
- lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
- lib/shared/bucketing-assembly-script/assembly/types/target.ts
- prevent bucketing logic from throwing on unknown comparators. Instead return false and log a warning
> fix: allow unknown comparators for forwards compatibility

- lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
- lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
- lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
- lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
- lib/shared/bucketing-assembly-script/assembly/types/target.ts
When a custom event is tracked, merge the current clientCustomData into the user's customData field when logging the event.
Do not merge in fields that are conflicted by an existing "privateCustomData" field.
> feat: add client custom data to user custom data when tracking events

- sdk/react/__mocks__/@devcycle/devcycle-js-sdk.ts
- sdk/react/src/useVariable.ts
- sdk/react/src/useVariableValue.test.tsx
Using `useVariable` will now only call the underlying JS SDK's `variable` method once, and store the result in a ref. It will still correctly re-render when onUpdate is called.
This prevents every render of a component that is using the `useVariable` hook from sending another variableEvaluated event (which could result in thousands of events)
> fix: react useVariable hook will only call the variable method once

- sdk/nodejs/__tests__/models/requestEvent.spec.ts
- sdk/nodejs/src/models/requestEvent.ts
> chore: remove date field and only send client date for request events

- lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
- lib/shared/bucketing-assembly-script/__tests__/eventQueue/eventQueueManager.test.ts
- lib/shared/bucketing-assembly-script/__tests__/setPlatformData.ts
- lib/shared/bucketing-assembly-script/__tests__/variable.test.ts
- lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
- lib/shared/bucketing-assembly-script/assembly/eventQueue/eventQueue.ts
- lib/shared/bucketing-assembly-script/assembly/index.ts
- lib/shared/bucketing-assembly-script/assembly/managers/eventQueueManager.ts
- lib/shared/bucketing-assembly-script/assembly/types/bucketedUserConfig.ts
- lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
- lib/shared/bucketing-assembly-script/assembly/types/dvcEvent.ts
- lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
- lib/shared/bucketing-assembly-script/assembly/types/feature.ts
- lib/shared/bucketing-assembly-script/assembly/types/featureConfiguration.ts
- lib/shared/bucketing-assembly-script/assembly/types/platformData.ts
- lib/shared/bucketing-assembly-script/assembly/types/target.ts
- lib/shared/bucketing-assembly-script/index.js
- lib/shared/bucketing-test-data/src/data/testData.ts
- lib/shared/bucketing/__test__/bucketing.test.ts
- sdk/nodejs/__tests__/eventQueue.test.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/utils/userBucketingHelper.ts
Add `variableForUser()` method in the WASM code that will return a specific variable result for a user, rather than fetching the full `generateBucketedConfigForUser()` every time. Also generate `aggVariableEvaluated` and `aggVariableDefaulted` from within the WASM code.
> DVC-6473 add variableForUser() method to WASM code

- lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
- lib/shared/bucketing-assembly-script/assembly/index.ts
- lib/shared/bucketing-assembly-script/assembly/managers/configDataManager.ts
- lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
- lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
- sdk/nodejs/src/environmentConfigManager.ts
- `setConfigDataWithEtag()` and `hasConfigDataForEtag()` methods will be used to check if we already have a config set for a specific etag value. This will mainly be used in our CF workers to optimize how often we set the config.
> DVC-6484 add hasConfigData() WASM method

- lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
- lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
- lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
- lib/shared/bucketing-assembly-script/assembly/types/bucketedUserConfig.ts
- lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
- lib/shared/bucketing-test-data/src/data/testData.ts
- lib/shared/bucketing/__test__/bucketing.test.ts
- lib/shared/bucketing/src/bucketing.ts
- lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
- lib/shared/types/src/types/config/configBody.ts
- sdk/nodejs/__tests__/eventQueue.test.ts
- we never ended up using `variableHashes` for what it was intended for, let's clean it up.
> DVC-6502 remove variableHashes from bucketed config output

- lib/shared/bucketing-assembly-script/__tests__/types/protobuf.test.ts
- lib/shared/bucketing-assembly-script/assembly/index.ts
- for preallocated buffer lengths used in the GO SDK
> DVC-6574 add variableForUser_PB_Preallocated method 

- lib/shared/bucketing-assembly-script/__tests__/types/protobuf.test.ts
- lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableDouble.ts
- lib/shared/bucketing-assembly-script/protobuf/variableForUserParams.proto
- add a string field to the NullableDouble proto object to prevent the output from including an `unmanaged` decorator
- this decorator is added by the as-proto library to "optimize performance" but actually causes a memory leak by creating unmanaged (and ungarbage-collected) objects each time a decode operation occurs
> fix: use dummy string field to stop unmanaged class decorator

- lib/shared/bucketing-assembly-script/protobuf/variableForUserParams.proto
Added in the go_package option to support protobuf file generation in Golang. The option should be ignored by other protobuf generators. 
Ultimately the .proto file in this project should be the record of authority and used by all other SDKs when generated protobuf classes
> Added proto file header for Go generation

- sdk/js/__tests__/EventEmitter.spec.js
- sdk/js/src/Client.ts
- sdk/js/src/EventEmitter.ts
this means the handler is called in a different thread than our regular config fetching code, so we don't catch exceptions thrown in the callback. 
every time subscribe/ unsubscribe are called, i had to remove the whole event listener, update our event handler store, and then add the listener again - not sure if there's a better way to do this? but since i'm using a wrapper to call multiple handlers, there doesn't seem to be a better way to edit the list of handlers in place
> Dispatch real events in eventEmitter

- lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
- lib/shared/bucketing-assembly-script/assembly/index.ts
- lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
- lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
- sdk/nodejs/__tests__/environmentConfigManager.spec.ts
- sdk/nodejs/src/__mocks__/bucketing.ts
- sdk/nodejs/src/environmentConfigManager.ts
- Add `setConfigDataUTF8()` and `setConfigDataUTF8Preallocated` methods to the bucketing AS lib for use with GO SDK to avoid casing of UTF8 JSON data -> UTF16 String in AS -> UTF8 String for JSON decoding in AS.
> Add setConfigDataUTF8() method to Bucketing AS

- lib/shared/bucketing-assembly-script/__tests__/types/platformData.test.ts
- lib/shared/bucketing-assembly-script/assembly/index.ts
- lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
- lib/shared/bucketing-assembly-script/assembly/types/platformData.ts
Extends the pattern we used with setConfigDataUTF8() to cover setting platform data and client custom data
The idea it to provide methods that will ensure all the json string data is encoded properly inside of the WASM
> DVC-6731 - Adding UTF8 functions for platform data and client custom data

- lib/shared/bucketing-assembly-script/__tests__/types/dvcUser.test.ts
- lib/shared/bucketing-assembly-script/assembly/index.ts
- lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
- lib/shared/bucketing-assembly-script/assembly/types/dvcUser.ts
When working in protobuf we need to export the getBucketedConfigForUser() data as a UTF8 encoded Uint8Array instead of the fake utf-16 strings we were using before, otherwise special characters get corrupted
> Adding UTF8 version of getBucketedConfigForUser

- lib/shared/types/package.json
- lib/shared/types/project.json
- sdk/js/package.json
- sdk/js/project.json
A user is trying to get the devcycle-js-sdk working with Angular 8, whose compiler depends on a max typescript version of 3.5.9. Our sdk and shared types packages are transpiled with a version of typescript beyond that range, so the types it emits are incompatible with the older typescript compiler.
Using `downlevel-dts` we're able to emit 3.5 compatible types, and using `typesVersions` in `package.json`, we're able to tell versions of typescript lower than 4 where to find them.
> chore(typescript): emit 3.5 types

- lib/shared/types/project.json
- sdk/js/project.json
I hadn't specified that emit-legacy-types depended on build, so build was happening after emit-legacy-types - effectively meaning that emit-legacy-types had nothing to work with since it's meant to run against the built files
> fix: dependsOn hierarchy for legacy types

- lib/shared/bucketing-assembly-script/__tests__/types/protobuf.test.ts
- lib/shared/bucketing-assembly-script/assembly/types/protobuf-generated/NullableDouble.ts
- lib/shared/bucketing-assembly-script/protobuf/compiled.d.ts
- lib/shared/bucketing-assembly-script/protobuf/compiled.js
- lib/shared/bucketing-assembly-script/protobuf/variableForUserParams.proto
Removed the dummy string for NullableDouble now that the `@unmanaged` bug in as-proto is fixed
> DVC-6674 - removed workaround for as-proto bug

- package.json
- sdk/react-native/src/index.ts
- sdk/react/src/index.ts
- yarn.lock
- React SDK  exports `DVClient, DVCUser, DVCVariableValue` from JS SDK
- React-Native SDK exports `DVClient, DVCUser, DVCVariableValue` from React SDK that is re-exporting the JS SDK types
> DVC-6965 [fix]: export JS SDK types from React and React-Native SDKs

- lib/shared/bucketing-assembly-script/protobuf/variableForUserParams.proto
Added namespace option to the protobuf file that is necessary for the dotnet SDK changes
- want to ensure this version in `js-sdks` remains the source of truth for protobuf for all SDKs
> Adding c# option to the protobuf so it is consistent with dotnet SDK

- sdk/js/__tests__/EventEmitter.spec.js
- sdk/js/src/Client.ts
- sdk/js/src/EventEmitter.ts
In order to hook up to datadogs feature flag monitoring, we need to know when a variable has been evaluated. Possibly overkill, but I created a new event that is emitted whenever a variable is evaluated, and plan to try hooking datadog's tracking up to that. Apologies for the first commit in this PR, which is exclusively auto-formatting. Real changes are in the second commit.
> feat: emit variable evaluated event

- sdk/js/__tests__/EventEmitter.spec.js
- sdk/js/src/Client.ts
- sdk/js/src/EventEmitter.ts
- sdk/js/src/types.ts
- yarn.lock
Noticed that variableUpdated was passing the key and the variable object to the handler so did the same with variableEvaluated, also updated the subscribe overrides and the accompanying jsdocs.
> chore: adopt existing signature, add types

- lib/shared/types/src/types/config/models/variable.ts
- sdk/js/src/Client.test.ts
- sdk/js/src/Client.ts
- sdk/js/src/types.ts
- sdk/react/src/useDVCClient.ts
- sdk/react/src/useVariable.ts
- sdk/react/src/useVariableValue.ts
Now you can define a generic arg to specify the set of variable keys and default values that are allowed in the JS client:
> chore: add generic arg for restricting possible types of variables in JS and React

- .eslintrc.json
- examples/js/web-elements-app/src/app/app.element.ts
- examples/nodejs-cloud/js/src/main.js
- examples/nodejs-cloud/typescript/src/main.ts
- examples/nodejs-local/js/src/main.js
- examples/nodejs-local/typescript/src/main.ts
- lib/shared/types/src/types/config/models/variable.ts
- sdk/js/__tests__/Client.spec.js
- sdk/js/src/Client.ts
- sdk/js/src/User.ts
- sdk/js/src/types.ts
- sdk/nodejs/__tests__/client.spec.ts
- sdk/nodejs/__tests__/cloudClient.spec.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/cloudClient.ts
Adding `variableValue()` method to all our JS SDKs so that you can retrieve a variable's value without needing to do: `dvc.variable('key', true).value`
> add variableValue() method to NodeJS Local / Cloud + JS SDK

- tsconfig.base.json
Addresses: https://github.com/DevCycleHQ/js-sdks/issues/488
> fix: enable inline sources to avoid parsing errors

- lib/shared/bucketing-assembly-script/index.js
this allows for devcycle to be used in esm runtime as `node:fs/promises`  since this error is being thrown 
```
Error initializing DevCycle: UserError: Cannot find module 'node:fs/promises'
```
> [feat] add support for using devcycle in esm runtime

- sdk/js/src/StreamingConnection.ts
- an error was previously being thrown when using the React SDK in Next while server rendering, because the EventSource did not exist on the serverside
- the SDK in general is supposed to be fine with running on the server and just log appropriate warnings
- this error wasn't seen before because it was being caught by the previous implementation inside the promise
- if EventSource is not defined, skip starting the streaming connection and log a warning.
> fix: dont open streaming connection when EventSource is not available

- .github/workflows/run-test-harness.yml
- package.json
- sdk/openfeature-nodejs-provider/__tests__/DevCycleProvider.test.ts
- sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
- yarn.lock
- Update OpenFeature provider to support changes in spec: https://github.com/open-feature/js-sdk/releases/tag/js-sdk-v1.3.0
- adds support for `initialize()` and `onClose()` methods
- adds support for `flagMetadata` setting params: `type` / `isDefaulted` / `defaultValue`
> fix: DVC-7694 update OpenFeature provider to support 1.3.0

- .github/workflows/run-test-harness.yml
- examples/js/web-elements-app/src/main.ts
- sdk/js/src/Request.ts
- add optional chaining to remove unwanted type errors
- fix: only return `errorString` when it's defined
> fix: only return errorString when its defined

- .gitignore
- .yarn/patches/@nx-js-npm-16.3.2-a543eca792.patch
- package.json
- yarn.lock
Temporarily patch the `@nx/js` package using `yarn patch` to fix the bug where Nx is adding devDependencies to dependencies, breaking our build.
The issue is described here:
https://github.com/nrwl/nx/issues/17758
For a diff with the changes being applied in the patch, see this Nx PR:
https://github.com/nrwl/nx/pull/17802
> chore: patch nx js package to avoid adding devDependencies

- lib/shared/types/src/types/config/models/variable.ts
- sdk/js/src/index.test.ts
- sdk/js/src/index.ts
- sdk/js/src/types.ts
- sdk/openfeature-nodejs-provider/src/DevCycleProvider.ts
- fix not being able to pass a type generic to the `initialize` call for the JS SDK
- fix the definition of DVCJSON to accurately reflect what the platform currently supports.
> fix: type generic arg on js client

- sdk/js/src/types.ts
- add missing `variableValue` to exported types
> fix: add variableValue method to exported types

- package.json
- sdk/react/__mocks__/@devcycle/js-client-sdk.ts
- sdk/react/mockData/mockConfig.ts
- sdk/react/package.json
- sdk/react/src/useVariable.ts
- sdk/react/src/useVariableValue.integration.test.tsx
- sdk/react/src/useVariableValue.test.tsx
- yarn.lock
* the `useVariable` method now uses the JS SDK client's `subscribe` method to listen for variable updates instead of a variable's `onUpdate` method. This fixes the bug where multiple components calling `useVariable`/`useVariableValue` would result in only the last calling component to re-render when there is an update
> fix: issue with re-rendering component React SDK

- examples/nodejs-local/typescript/src/benchmarkDVC.ts
- sdk/nodejs/__tests__/environmentConfigManager.spec.ts
- sdk/nodejs/src/bucketing.ts
- sdk/nodejs/src/environmentConfigManager.ts
- sdk/nodejs/src/request.ts
- yarn.lock
Fix a couple of small issues found when debugging the NodeJS SDK
- fix the nodeJS SDK failing to use the debug WASM when debug logging is set.
- fix 'Failed to download config' debug log from 304 response
> fix: running debug WASM when debug logging is set, fix 'Failed to download config' debug log from 304 response

- lib/shared/types/src/types/config/models/featureConfiguration.ts
- add field to denote an override targeting rule in the config
> chore: add targeting type field

- lib/shared/bucketing-assembly-script/package.json
- yarn.lock
- explicitly depend on protobufjs for the assemblyscript lib, because it requires it in its source files
- fixes using the nodejs sdk in pnpm installations
> fix: add protobufjs dependency to assemblyscript lib

- sdk/js/src/Client.ts
- sdk/js/src/index.ts
- refactor addEventListener for page hide events to be within the Client definition instead of on initialize
- add removeEventListener for page hide events (if defined)
- proposed fix for: https://github.com/DevCycleHQ/js-sdks/issues/550
> fix: cleanup EventListener for Page Hide event 

- sdk/js/src/Client.ts
- sdk/react/__mocks__/@devcycle/js-client-sdk.ts
- sdk/react/src/DevCycleProvider.tsx
- sdk/react/src/context.ts
- sdk/react/src/useIsDevCycleInitialized.test.tsx
- sdk/react/src/useIsDevCycleInitialized.ts
- update React provider to include information on client initialization status
- update `useIsDevCycleInitialized` to read from that context rather than maintaining its own state and initialization listener
- add public `isInitialized` property to JS SDK client
> fix: DVC initialized hook rerender

- lib/shared/bucketing-assembly-script/index.js
When bundling a project with webpack that contains the node sdk, the build will fail because `bucketing-lib.debug.js` cannot be found
`instantiate` is already loaded based on the release type `const { instantiate } = require(`./build/bucketing-lib.${releaseStr}.js`)`
Remove extra `require` that is specific to debug import
> fix: Use dynamic import of bucketing-lib for debug/release

- .github/workflows/release.yml
This just allows testing the workflow on a branch later - the file needs to be merged first.
> ci: Add a skeleton release workflow to allow testing on GA

- lib/shared/types/project.json
- lib/shared/types/tsconfig.lib.es5.json
- package.json
- sdk/js/project.json
- sdk/js/tsconfig.lib.es5.json
- sdk/react-native-expo/.eslintrc.json
- sdk/react-native-expo/README.md
- sdk/react-native-expo/babel.config.json
- sdk/react-native-expo/jest.config.ts
- sdk/react-native-expo/package.json
- sdk/react-native-expo/project.json
- sdk/react-native-expo/src/DevCycleProvider.tsx
- sdk/react-native-expo/src/ReactNativeCacheStore.ts
- sdk/react-native-expo/src/index.ts
- sdk/react-native-expo/src/withDevCycleProvider.ts
- sdk/react-native-expo/test-setup.ts
- sdk/react-native-expo/tsconfig.json
- sdk/react-native-expo/tsconfig.lib.json
- sdk/react-native-expo/tsconfig.spec.json
- sdk/react/project.json
- sdk/react/tsconfig.lib.es5.json
- tsconfig.base.json
- yarn.lock
`nx run react-native-expo:build:expo`
Adds a new package, `react-native-expo`, that is mostly a duplicate of `react-native`, but it triggers new `build:es5` targets in each of the react-native sdk's dependencies, via an executor that then bundles the es5 transpiled dependencies into the package.
Ideally this doesn't remain necessary for long, objective here is to not compromise the react-native sdk, and to allow us to make expo related adjustments as they become necessary.
- DVC-5386
> feat: add react-native-expo package

- sdk/js/__tests__/Client.spec.js
- sdk/js/src/Client.ts
- sdk/js/src/types.ts
- sdk/react/src/initializeDevCycleClient.ts
- add bootstrapConfig option to provide initial config to JS SDK
> feat: add option for bootstrapping config in JS SDK

- sdk/js/__tests__/Client.spec.js
- sdk/js/src/Client.ts
- sdk/js/src/types.ts
In [this PR](https://github.com/DevCycleHQ/js-sdks/commit/beed17838888d8aedc53e520721fa5d3a934ec56#diff-7e88ae7eb811449dfe4a792952dab7d8accab565833b6a8a5764488a232d4325R191) there was a change that switched from using the populated user to using the initial user to check if the user is anonymous. 
`isAnonymous` would only be true on the initial user if the SDK is explicitly called with this property. The populated user will have isAnonymous set to true if a user id is not specified.
This would cause the cached anonymous user ID to be cleared on every initialization, resulting in more MAUs than expected.
> fix: Use populated user when checking if user is anonymous

- sdk/js/__tests__/Client.spec.js
- sdk/js/src/Client.ts
- sdk/react/src/useIsDevCycleInitialized.test.tsx
- add tests for deferred mode and bootstrap  config mode for react sdk initialization
- ensure that boostrap config leads to an "initialized" first render
> fix: add tests for init in deferred mode and with boostrap config

- .github/workflows/nx-affected-test.yml
- .github/workflows/run-test-harness.yml
This step takes a few minutes on every run, but I'm pretty sure it's no longer required.
> fix: Remove protoc installation in workflows

- .yarn/patches/@altack-nx-bundlefy-npm-0.16.0-fc464002e3.patch
- lib/shared/types/project.json
- package.json
- sdk/js/project.json
- sdk/react-native-expo/project.json
- sdk/react/project.json
- yarn.lock
- output es5 builds to an es5 subdirectory in dist/
- patch the bundlefy package so that it looks at our build:es5 target to determine the path to copy the output files from
> fix: separate es5 build outputs and patch bundlefy to use the correct target

- scripts/lerna-version-ci.sh
- disable lerna's change detection logic and rely only on force-publish
> chore: add ignore-changes flag

- scripts/lerna-version-ci.sh
- sdk/nextjs/package.json
- fix the release process by allowing nextjs releases to be tagged
- the sdk still has no "publish" task so it won't publish any of these versions
> chore: fix release by allowing nextjs tags

- sdk/nextjs/README.md
- sdk/nextjs/project.json
- publish readme with package
- add more details about canary
> chore: fix nextjs readme

- e2e/nextjs/app-router/app/yarn.lock
- sdk/nextjs/README.md
- sdk/nextjs/src/common/invalidateConfig.ts
- sdk/nextjs/src/server/DevCycleServersideProvider.tsx
- sdk/nextjs/src/server/bucketing.ts
- sdk/nextjs/src/server/initialize.ts
- sdk/nextjs/src/server/requestContext.ts
- sdk/nextjs/src/server/requests.ts
- sdk/nextjs/src/server/userAgent.ts
- swap React cache for async local storage
- this is one step to removing requirement for react canary build
> fix: async local storage

- sdk/react/src/DevCycleProvider.tsx
- sdk/react/src/useIsDevCycleInitialized.test.tsx
React in strict mode mounts and renders a component twice in development.
Our current DevCycleProvider calls `client.close` in its useEffect cleanup function, which is normally fine, except in strict mode it seems that the ref is "shared" between multiple mounts of a component. I think this is actually a bug in React:
https://github.com/facebook/react/issues/24670
To fix it, we basically need to not use a ref here and store the client in state instead. The state is properly "reset" when the component is re-mounted, so the "close" call that happens on the first instance's cleanup function does not cause the client instance on the second mount to close.
> fix: call close on correct reference to client

- e2e/nextjs/app-router/app/app/layout.tsx
- e2e/nextjs/app-router/app/app/page.tsx
- e2e/nextjs/app-router/app/app/shared.ts
- e2e/nextjs/app-router/app/package.json
- e2e/nextjs/app-router/app/yarn.lock
- e2e/nextjs/pages-router/app/package.json
- e2e/nextjs/pages-router/app/yarn.lock
- sdk/nextjs/src/client/DevCycleClientsideProvider.tsx
- sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
- sdk/nextjs/src/common/types.ts
- sdk/nextjs/src/server/getVariableValue.ts
- sdk/nextjs/src/server/initialize.ts
- sdk/nextjs/src/server/setupDevCycle.ts
- sometimes the initialize promise will resolve before the layout or other parts of the page are rendered
- in this case the previous implementation of streaming would cause hydration errors because the server would render its contents with the variable values, while the client would wait for the promise and re-render on the next pass after realizing it was resolved
- to fix this, the server basically needs to wait for the promise in a non-blocking way and then notify the client during the first render whether it is safe to `use` the promise because it has already resolved, thus receiving its resolved contents on the first render pass without blocking anything in streaming mode
- this also removes the requirement to await the getClientContext method, and brings the waiting of the user's …
> fix: streaming in cases where the promise resolves before the layout is rendered

- sdk/nextjs/src/server/allFeatures.ts
- sdk/nextjs/src/server/getAllVariables.ts
- sdk/nextjs/src/server/getVariableValue.ts
- sdk/nextjs/src/server/setupDevCycle.ts
- ensure that the callstack which originally kicks off the initialize promise ends up awaiting that promise directly, rather than indirectly through retrieving it back out of the React cache
- this should fix the DynamicRendering build errors
> fix: move promise await to fix static builds

- sdk/js-cloud-server/src/cloudClient.ts
- sdk/nodejs/__tests__/initialize.spec.ts
- sdk/nodejs/__tests__/open-feature-provider/DevCycleProvider.test.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/index.ts
- sdk/nodejs/src/open-feature-provider/DevCycleProvider.ts
We had to change approach from #714 as the OF libraries have NodeJS APIs. Now we just extend the `DevCycleCloudClient` with the `getOpenFeatureProvider()` method in the NodeJS SDK before exporting it for use.
> feat: update NodeJS SDK to enable getOpenFeatureProvider() for cloud bucketing

- sdk/openfeature-web-provider/package.json
- sdk/openfeature-web-provider/src/DevCycleProvider.ts
- yarn.lock
update OpenFeature web provider to emit `configUpdated` and `error` events, this will enable live-updates to work with the OpenFeature React SDK.
> feat: update OpenFeature web provider to emit configUpdated and error events

- sdk/openfeature-web-provider/src/DevCycleProvider.ts
Fix setting the OpenFeature Web Provider to actually export the EventsEmitter to make live-updates work in React. 
For context here is the Provider interface:
> fix: OpenFeature Web Provider exporting events emitter

- sdk/react/src/DevCycleProvider.tsx
Based on the answer here:
https://github.com/facebook/react/issues/27735#issuecomment-1885624506
due to some misunderstanding in what strict mode actually does, we were still causing the client to get erroneously closed in development when strict mode was enabled. 
Basically this fix makes it so that a client exists on initial render, and continues to exist and not get recreated when in production or without strict mode
With strict mode, the useEffect gets double-executed, which causes a cleanup of the client. But now it sets the ref to null in that case, and the second run of the useEffect re-creates the client when it sees that it is now null
> fix: react strictmode closing wrong client again

- .github/workflows/release.yml
- re-enable release process for js-sdks
- fixed grabbing the SDK_VERSION
> chore: re-enable js sdk release process

- package.json
- yarn.lock
- removes the @nrwl/jest package that was added during e2e test work. It's set to the wrong (newest) version and also packages have been renamed to @nx/*, and we already use `@nx/jest`
> chore: remove nrwl jest package

- sdk/nestjs/.eslintrc.json
- sdk/nestjs/mocks.ts
- sdk/nestjs/src/__mocks__/DevCycleClient.ts
- sdk/nestjs/src/__mocks__/DevCycleModule.ts
- sdk/nestjs/src/__mocks__/RequireVariableValue.ts
- sdk/nestjs/src/__mocks__/VariableValue.ts
- sdk/nestjs/src/__mocks__/index.ts
- sdk/nestjs/tsconfig.lib.json
The SDK can be mocked using `jest.mock('@devcycle/nestjs-server-sdk')`
Variable values can be mocked using the `mockVariables` method
```
const dvcClient = moduleRef.get<DevCycleClient>(
DevCycleClient,
) as MockDevCycleClient
dvcClient.mockVariables({ 'user-permissions': true })
```
> feat: Add mocks to nestjs sdk

- lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
- lib/shared/bucketing-assembly-script/assembly/testHelpers.ts
- lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
- lib/shared/bucketing-assembly-script/assembly/types/target.ts
- lib/shared/bucketing-test-data/src/data/largeConfig.ts
- lib/shared/bucketing-test-data/src/data/testData.ts
- lib/shared/bucketing/src/bucketing.ts
- lib/shared/types/src/types/config/models/audience.ts
- lib/shared/types/src/types/config/models/featureConfiguration.ts
The `_audience._id` field inside the targeting rules of the config is not used, but also will no longer exist due to the audience merge migration.
Update the types to omit this field and update the assembly script bucketing to remove it as well
> chore: remove audience _id field from config and update bucketing code

- lib/web-debugger/index.ts
- lib/web-debugger/package.json
- lib/web-debugger/react.tsx
- add js extensions to imports so it works in esmodules
- change package.json type to "module" since Nx is messing with it anyway and setting it to module
> fix: update imports to use js extensions for es modules

- examples/react/project.json
- examples/react/tsconfig.json
- examples/react/webpack.config.js
- lib/web-debugger/package.json
- tsconfig.base.json
Allow the React example app to properly resolve ".js" file imports from our libraries that need to specify imports that way.
> chore: Fix example apps resolution

- lib/shared/bucketing-assembly-script/assembly/index.ts
- lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
- lib/shared/bucketing-test-data/src/data/testData.ts
- lib/shared/config-manager/src/index.ts
- lib/shared/types/src/types/apis/sdk/serverSDKTypes.ts
- lib/shared/types/src/types/config/configBody.ts
- sdk/js-cloud-server/src/models/populatedUser.ts
- sdk/nodejs/.eslintrc.json
- sdk/nodejs/project.json
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/clientUser.ts
- sdk/nodejs/src/utils/userBucketingHelper.ts
- maintain a separate polling manager for the client version of the SDK
- assumes the client SDK is available under the server SDK key (it will be with R2)
- create correct user object for bucketing
> feat: nodejs bootstrapping mode

- sdk/js/src/index.ts
- remove the warning about window not being defined
- this appears any time the js sdk is executed on the server (which can happen in any SSR usecase) so it isn't really a useful warning. The SDK works without the window being defined
> fix: remove warning about window being undefined

- sdk/react-native-expo/package.json
- sdk/react-native/package.json
- fix: update `react-native` package.json `types` to `./index.cjs.d.ts` 
- fix: update `react-native-expo` package.json `types` to `./index.cjs.d.ts` 
- these changes are required as NX does not support remapping of the `types` field the same way it supports the `main` field in the package.json files
> fix: update react-native and react-native-expo TYPE path in package.json to the right file

- lib/shared/bucketing-assembly-script/__tests__/types/configBody.test.ts
- lib/shared/bucketing-assembly-script/assembly/helpers/murmurhash.ts
- lib/shared/bucketing-test-data/src/data/testData.ts
- lib/shared/types/src/types/config/models/featureConfiguration.ts
- package.json
- yarn.lock
not having the audience _id causes parsing issues with older versions of WASM, but the value isn't actually used. Going forward we can just set it to an empty string to make the parser happy
> chore: add back audience id field on config body type

- .github/workflows/nx-affected-e2e.yml
- sdk/react/src/withDevCycleProvider.tsx
Update the react SDK HOC to use forwardRef to assign any passed-in ref to the original wrapped component
> fix: Forward Refs in React SDK HOC

- scripts/lerna-version-ci.sh
Fixing issue from: https://github.com/DevCycleHQ/js-sdks/actions/runs/9287233188/job/25555727208
> chore: update lerna-version-ci.sh script to fix issue when there are no tags

- sdk/react-native-expo/package.json
- sdk/react-native-expo/project.json
- sdk/react-native-expo/tsconfig.lib.json
- sdk/react-native/package.json
- sdk/react-native/project.json
- sdk/react-native/tsconfig.lib.json
- yarn.lock
The `build:es5` builds for `react-native` and `react-native-expo` were adding polyfills for Promises and other functions, these polyfills are not required anymore. But do require increasing our minimum support levels to:
- react-native: `0.69.0`
- react: `18.0.0`
> chore: update react-native and react-native-expo build system to remove polyfills

- lib/shared/config-manager/src/index.ts
- sdk/nodejs/__tests__/client.spec.ts
- sdk/nodejs/src/client.ts
The first config request failing during initialization would result in the `_isInitalized` boolean never getting set. This would permanent break the variables/features/track calls since `_isInitialized` would only be set to true if the first config request succeeded.
The fix was to expose the `configHelper`'s `hasConfig` property to the client, and to use that property to determine whether the variable calls should log a warning and return the default. This allows the sdk to recover if/when a subsequent config request succeeds.
Additionally, the `_isInitialized` flag is now being set to true in the `catch` case of the initialized promise. This is so that the `track` call can continue to use that flag as a gate since it doesn't require a config, just the event queue being initialized.
> fix: sdk not recovering from failure on first config fetch

- lib/shared/config-manager/__tests__/environmentConfigManager.spec.ts
- lib/shared/config-manager/src/index.ts
> fix: Node.js SSE reconnecting after error on 304 CDN response

- lib/shared/bucketing-assembly-script/index.d.ts
- lib/shared/config-manager/__tests__/environmentConfigManager.spec.ts
- lib/shared/config-manager/src/index.ts
- sdk/nodejs/__tests__/client.spec.ts
- sdk/nodejs/__tests__/eventQueue.test.ts
- sdk/nodejs/__tests__/utils/setPlatformData.ts
- sdk/nodejs/src/__mocks__/bucketing.ts
- sdk/nodejs/src/bucketing.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/eventQueue.ts
- sdk/nodejs/src/utils/userBucketingHelper.ts
- instantiate WASM module once per client, rather than storing in module cache
- should resolve issues with clients being reloaded in HMR dev servers without the underlying WASM memory being reset
> fix: create WASM instance per NodeJS client

- sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
- sdk/nextjs/src/client/internal/useRerenderOnVariableChange.ts
- sdk/nextjs/src/common/invalidateConfig.ts
- sdk/nextjs/src/pages/appWithDevCycle.tsx
- sdk/nextjs/src/server/bucketing.ts
- sdk/nextjs/src/server/initialize.ts
- sdk/nextjs/src/server/requests.ts
- sdk/nextjs/src/server/setupDevCycle.tsx
- Remove the lastModified logic from the invalidation since the lastModified date wont actually be accessible on the client side due to the config using the server token
- add clientSDKKey as a parameter to the initialize call so it can be added as a tag on the server side
- Tested manually
> fix: Add clientSDKKey as a tag on the config request so it can be invalidated from the client side

- lib/shared/types/src/types/config/models/audience.ts
- lib/shared/types/src/types/config/models/featureConfiguration.ts
- add comparator types to the shared types
> feat: add comparators to ConfigBody

- sdk/nodejs/__tests__/eventQueue.test.ts
- sdk/nodejs/src/eventQueue.ts
- filtered out the `logger` option when initializing the event queue in the bucketing library to avoid JSON.stringifying a logger that could be passed in, e.g. `winston`. If the logger has a circular dependency, stringifying it will cause an error. Since the event queue options don't utilize the logger anyway, only pass in the options it expects
> chore: fixed passing in logger object when stringifying to prevent circular json error

- lib/shared/vercel-edge-config/src/edge-config.ts
- sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
- sdk/nextjs/src/common/ConfigSource.ts
- sdk/nextjs/src/common/types.ts
- sdk/nextjs/src/pages/bucketing.ts
- sdk/nextjs/src/server/bucketing.ts
- sdk/nextjs/src/server/initialize.ts
- sdk/nextjs/src/server/setupDevCycle.tsx
- make sure edge config always returns a config in Nextjs by disabling the last modified check in that SDK
- fix the type definitions so that the edge config client is compatible with Nextjs types
> fix: disable last modified check on vercel edge config and fix type definitions

- sdk/js/src/Variable.ts
- sdk/js/src/types.ts
> fix: changed type from DVCVariableValue to type VariableTypeAlias

- sdk/js/src/Client.ts
- sdk/js/src/types.ts
When realtime updates are disabled, there should be no page background watcher that tries to refresh the config when foregrounded. The config should never be updated after initialization, unless identity is changed.
> fix: disable background refresh when realtime is disabled

- lib/shared/bucketing-assembly-script/__tests__/bucketing/segmentation.test.ts
- lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
- lib/shared/bucketing-assembly-script/assembly/helpers/lodashHelpers.ts
- lib/shared/bucketing-assembly-script/assembly/types/target.ts
- add `startWith` and `endWith` comparators to bucketing wasm code
> feat: add new comparators for bucketing assembly script

- lib/shared/bucketing-test-data/src/data/testData.ts
- lib/shared/bucketing/__tests__/bucketing.test.ts
- lib/shared/bucketing/src/bucketing.ts
- use `bucketingKey` if user has it defined in `customData`, otherwise use `"null"` to bucket users that don't have a customData value
> feat: use bucketingKey from users custom data

- lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
- lib/shared/bucketing-assembly-script/__tests__/helpers/configWithBucketingKey.ts
- lib/shared/bucketing-assembly-script/__tests__/types/configBodyV2.test.ts
- lib/shared/bucketing-assembly-script/assembly/bucketing/bucketing.ts
- lib/shared/bucketing-assembly-script/assembly/helpers/jsonHelpers.ts
- lib/shared/bucketing-assembly-script/assembly/helpers/murmurhash.ts
- lib/shared/bucketing-assembly-script/assembly/index.ts
- lib/shared/bucketing-assembly-script/assembly/managers/configDataManager.ts
- lib/shared/bucketing-assembly-script/assembly/types/configBodyV2.ts
- lib/shared/bucketing-assembly-script/assembly/types/featureV2.ts
- lib/shared/bucketing-assembly-script/assembly/types/target.ts
- lib/shared/bucketing-assembly-script/assembly/types/targetV2.ts
- added tests for bucketing key 
- used bucketing key if it exists instead of user_id
> feat: added bucketing key logic to shared-bucketing-as

- sdk/js/src/ConfigRequestConsolidator.ts
- fix: reset `currentPromise` in the config request consolidation queue, including if there is an error while fetching
> fix: reset current promise after every config request

- lib/shared/config-manager/__tests__/environmentConfigManager.spec.ts
- lib/shared/config-manager/src/CDNConfigSource.ts
> chore: use v2 configs in nodejs

- lib/web-debugger/src/initializeDevCycleDebugger.ts
- tsconfig.base.json
- limit number of live events stored by debugger
- debounce updateIframeData function so that it doesn't trigger once for each evaluation in a scenario where lots of variables are being evaluated.
> fix: debounce iframe updates and limit size of stored events

- sdk/js/__tests__/Client.test.ts
- sdk/js/src/Client.ts
- sdk/js/src/EventQueue.ts
- sdk/js/src/index.ts
- sdk/js/src/types.ts
- sdk/nextjs/index.ts
- sdk/nextjs/src/server/setupDevCycle.tsx
- sdk/react/src/index.ts
- sdk/react/src/types.ts
- sdk/react/src/useDevCycleClient.ts
- sdk/react/src/withDevCycleProvider.tsx
- add a generic type arg for specifying the type of the user's custom data
- enforce via types that the custom data is set correctly in the user interfaces of the JS, React and Next SDKs
> feat: add custom property generic to SDKs

- e2e/nextjs/pages-router/app/pages/self-targeting/index.tsx
- e2e/nextjs/pages-router/app/yarn.lock
- e2e/nextjs/pages-router/tests/pages-router.spec.ts
- sdk/nextjs/src/common/serializeUser.ts
- sdk/nextjs/src/pages/bucketing.ts
- sdk/nextjs/src/pages/requests.ts
- add support for self targeting in Next js pages router by fetching from SDK API when using a debug user
> feat: support self-targeting in pages router

- sdk/js/src/Client.ts
- sdk/js/src/EventQueue.ts
- sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
- sdk/nextjs/src/client/internal/context.ts
- sdk/nextjs/src/client/internal/useDevCycleClient.ts
- sdk/nextjs/src/client/useDevCycleClient.ts
- disable events in the JS client instantiated in the ClientsideProvider for Nextjs while running on the server
- don't create an event queue in the JS client when events are disabled
> fix: disable next events serverside in the ClientSide provider

- sdk/nextjs/src/server/bucketing.ts
- sdk/nextjs/src/server/requests.ts
- wrap the construction of the DVCPopulatedUser in a per-request cache so that it doesn't recreate from scratch on each call to `useVariableValue`
- this also makes sure we're using the same timestamps for the user across the request
- caching this means that caching the bucketed config result now works as intended
- wrap the call to the SDK API in a cache as well, because the fetch call is being treated as "not cacheable" by Next for some reason
> fix: caching of user and bucketed config

- sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
- switch to using a useEffect for suspended data synchronization in the Next SDK
- calling any kind of setState during a render will always lead to errors in React, it should only be done in effects or event handlers
> fix: use a useEffect for suspended data synchronization

- sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
- handle synchronizing to Nextjs client by attaching a handler to the promise directly
> fix: attach sync call directly to promise

- sdk/js-cloud-server/src/cloudClient.ts
- there is logic in the cloud sdk for throwing if its not a 404 from bucketing api, we should not be loggin error here as well since we send a defaulted variable anyways
> feat: update the error on getVariable to not log on default variable

- sdk/nextjs/src/common/invalidateConfig.ts
- fix: cleanup debugging `console.log` from NextJS `invalidateConfig` method
- addresses: https://github.com/DevCycleHQ/js-sdks/issues/993
> fix: remove leftover console.log from invalidateConfig

- dev-apps/openfeature-nodejs/src/main.ts
- sdk/nodejs/package.json
- sdk/openfeature-web-provider/package.json
- yarn.lock
> fix: OpenFeature peer dependancy

- sdk/nextjs/src/server/bucketing.ts
- sdk/nextjs/src/server/requests.ts
- memoize the CDN call for fetch manually since Next docs don't seem to be able to decide whether fetch is being memoized or not
> fix: memoize config CDN call

- sdk/nodejs/__tests__/eventQueue.test.ts
- sdk/nodejs/src/eventQueue.ts
- If the sdk key is invalid, close the event queue
> fix: fixed retrying logic for invalid sdk key

- package.json
- sdk/nestjs/src/VariableValue.test.ts
- yarn.lock
- update Typescript to fix compiler's handling of empty interface `keyof` declarations
> chore: typescript 5.7

- sdk/nextjs/src/client/internal/InternalDevCycleClientsideProvider.tsx
- instead of calling "use" on the server data promise, just use the serverData we already have available on this code path
- `use` seems to have some weird edge cases that are probably bugs in Next/React
> fix: use resolved server data in non-streaming mode

- sdk/nextjs/src/server/bucketing.ts
- sdk/nextjs/src/server/initialize.ts
- improve next js speeds by parallelizing config CDN fetch and user getter call
> chore: parallelize config fetch

- lib/shared/vercel-edge-config/package.json
- lib/shared/vercel-edge-config/src/edge-config.spec.ts
- lib/shared/vercel-edge-config/src/edge-config.ts
- yarn.lock
- fix vercel edge config adapter so that it calls class transformer on the config data after retrieval
> fix: vercel edge config adapter to calls class-transform

- .github/workflows/nx-affected-e2e.yml
- e2e/js/js-cloud-server/yarn.lock
- e2e/nextjs/app-router/app/yarn.lock
- e2e/nextjs/pages-router/app/yarn.lock
- lib/shared/config-manager/__tests__/environmentConfigManager.spec.ts
- lib/shared/config-manager/src/index.ts
- lib/shared/types/src/types/apis/sdk/serverSDKTypes.ts
- package.json
- yarn.lock
Change the default bahaviour of the NodeJS SDK to default to using SSE connections.
> feat: default sse enabled for NodeJS SDK

- sdk/nextjs/src/client/useTrack.ts
- Update to Next.js SDK to use `useCallback()` to memoize the `client.track()` call in `useTrack`
> fix: memoize track() call in next.js SDK

- sdk/js/__tests__/Request.spec.ts
- sdk/js/src/Client.ts
- sdk/js/src/Request.ts
- sdk/js/src/User.ts
- sdk/openfeature-react-provider/.babelrc
- sdk/openfeature-react-provider/.eslintrc.json
- sdk/openfeature-react-provider/README.md
- sdk/openfeature-react-provider/__mocks__/@devcycle/js-client-sdk.ts
- sdk/openfeature-react-provider/__tests__/DevCycleReactProvider.test.ts
- sdk/openfeature-react-provider/jest.config.ts
- sdk/openfeature-react-provider/package.json
- sdk/openfeature-react-provider/project.json
- sdk/openfeature-react-provider/src/index.ts
- sdk/openfeature-react-provider/strategy.ts
- sdk/openfeature-react-provider/tsconfig.json
- sdk/openfeature-react-provider/tsconfig.lib.json
- sdk/openfeature-react-provider/tsconfig.spec.json
- sdk/openfeature-web-provider/README.md
- sdk/openfeature-web-provider/package.json
- tsconfig.base.json
- yarn.lock
- create new @devcycle/openfeature-react-provider 1.0.0 package to track usage of Devcycle with the React OpenFeature SDK
- update @devcycle/openfeature-web-provider to 1.0.0
- cleanup README.md files
> feat: create openfeature-react-provider to track usage of react OF provider

- dev-apps/openfeature-nodejs/src/main.ts
- sdk/nodejs/__tests__/initialize.spec.ts
- sdk/nodejs/__tests__/open-feature-provider/DevCycleProvider.test.ts
- sdk/nodejs/package.json
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/index.ts
- sdk/nodejs/src/open-feature/DevCycleProvider.ts
- yarn.lock
- Change OpenFeature imports from a dynamic import (which has always caused us problems), to a straight require.
- This is a bit of a reversion to the old way we had it setup, and will require all SDK users using Yarn to add the OpenFeature packages.
- But this will mean that all SDKs will come with OpenFeature setup (good thing!), and the `getOpenFeatureProvider()` method no longer needs to be `async` which was causing complications with SDKs like NestJS.
> feat: change OpenFeature imports and DevCycleProvider interface

- lib/shared/types/src/types/apis/sdk/serverSDKTypes.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/index.ts
- sdk/openfeature-nestjs-provider/.babelrc
- sdk/openfeature-nestjs-provider/.eslintrc.json
- sdk/openfeature-nestjs-provider/README.md
- sdk/openfeature-nestjs-provider/jest.config.ts
- sdk/openfeature-nestjs-provider/package.json
- sdk/openfeature-nestjs-provider/project.json
- sdk/openfeature-nestjs-provider/src/index.ts
- sdk/openfeature-nestjs-provider/tsconfig.json
- sdk/openfeature-nestjs-provider/tsconfig.lib.json
- sdk/openfeature-nestjs-provider/tsconfig.spec.json
- yarn.lock
- Create new `@devcycle/openfeature-nestjs-provider` package to set `sdkPlatform` when using OpenFeatures NestJS SDK with DevCycle.
> feat: create @devcycle/openfeature-nestjs-provider to set sdkPlatform metadata

- sdk/openfeature-nestjs-provider/src/index.ts
- update the nestJS OF provider to use the new DevCycleProvider to set the sdkPlatform
> feat: update the nestJS OF provider to use the new DevCycleProvider to set the sdkPlatform

- tsconfig.base.json
> chore: add missing tsconfig.base refrences

- lib/shared/bucketing/jest.config.ts
- sdk/js-cloud-server/jest.config.ts
- sdk/js/jest.config.ts
- sdk/nodejs/__tests__/client.spec.ts
- sdk/nodejs/jest.config.ts
- sdk/nodejs/src/__mocks__/bucketing.ts
- sdk/nodejs/src/client.ts
- sdk/openfeature-angular-provider/jest.config.ts
- sdk/openfeature-nestjs-provider/jest.config.ts
- sdk/openfeature-react-provider/jest.config.ts
- sdk/openfeature-web-provider/jest.config.ts
> feat: add setClientCustomData to the local nodejs server sdk

- sdk/nodejs/src/client.ts
- setClientCustomData to not throw error to match test harness
> fix: setClientCustomData to not throw error to match test harness

- lib/shared/bucketing-assembly-script/index.js
- sdk/nodejs/package.json
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/clientUser.ts
- yarn.lock
- see clientUser.ts comment for description of why this is needed.
- Currently all Node.js/Next.js Typescript projects will error out like this:
> fix: js-client-sdk missing dependancy issue with nodejs-server-sdk

- .eslintrc.json
- sdk/js/__tests__/RequestEvent.spec.js
- sdk/js/src/EventQueue.ts
- sdk/js/src/Request.ts
- sdk/js/src/RequestEvent.ts
- sdk/js/src/utils.ts
- filter `featureVars` in js-sdk using `settings.filterFeatureVars` and `variable._feature`
> feat: filter featureVars for variable events in js-sdk

- .eslintrc.json
- .github/workflows/cf-worker-example-test.yml
- lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
- sdk/js/__tests__/RequestEvent.spec.js
- sdk/js/src/EventQueue.ts
- sdk/js/src/Request.ts
- sdk/js/src/RequestEvent.ts
- sdk/js/src/utils.ts
- adds the `_feature` id to the Variables returned by the SDK API. This will be used on the client SDKs to know how to filter their `featureVars` for each `variableEvaluation` / `variableDefault` event.
- updates the `BucketedUserConfig` schema with an optional `settings.filterFeatureVars` boolean to signal to the SDKs that `_feature` params should exist on Variables in the config and they should filter `featureVars`. This is to let SDKs filter `featureVars ` to an empty object if there isn't a `_feature` for a variable.
> chore: add _feature to SDKVariable on clientSDKAPI

- .github/workflows/run-test-harness.yml
Potential fix for [https://github.com/DevCycleHQ/js-sdks/security/code-scanning/182](https://github.com/DevCycleHQ/js-sdks/security/code-scanning/182)
To fix the issue, we will add a `permissions` block at the workflow level to explicitly define the least privileges required. Based on the workflow's steps, it primarily reads repository contents and uses a secret token for authentication. Therefore, the `contents: read` permission is sufficient. If additional permissions are required in the future, they can be added explicitly.
The `permissions` block will be added at the root of the workflow file, just below the `name` field, to apply to all jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: Potential fix for code scanning alert no. 182: Workflow does not contain permissions

- .github/workflows/update-of-sdk.yml
Potential fix for [https://github.com/DevCycleHQ/js-sdks/security/code-scanning/173](https://github.com/DevCycleHQ/js-sdks/security/code-scanning/173)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will explicitly define the minimal permissions required for the workflow to function correctly. Based on the operations in the workflow, the following permissions are needed:
- `contents: write` for committing and pushing changes to the repository.
- `pull-requests: write` for creating pull requests.
The `permissions` block will be added at the root level, applying to all jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: Potential fix for code scanning alert no. 173: Workflow does not contain permissions

- .github/workflows/cf-worker-example-test.yml
Potential fix for [https://github.com/DevCycleHQ/js-sdks/security/code-scanning/177](https://github.com/DevCycleHQ/js-sdks/security/code-scanning/177)
To fix the issue, add a `permissions` block at the root of the workflow file to explicitly define the minimal permissions required. Since the workflow only reads repository contents and does not perform any write operations, the `contents: read` permission is sufficient. This change ensures that the workflow does not inadvertently gain unnecessary write permissions.
The `permissions` block should be added immediately after the `name` field in the workflow file.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> chore: Potential fix for code scanning alert no. 177: Workflow does not contain permissions

- lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
- lib/shared/bucketing-assembly-script/assembly/bucketing/segmentation.ts
- lib/shared/bucketing-test-data/src/data/testData.ts
- lib/shared/bucketing/__tests__/bucketing.test.ts
- fix: check all filters defined when the `filter.operator` is an OR before returning true or false
> fix: check all filters on top level ORs for a truthy match before returning false

- sdk/js/__tests__/EventEmitter.spec.js
- sdk/js/src/EventEmitter.ts
- avoid removing last handler when unsubscribing an unknown callback
- add test to cover unsubscribing a non-existent handler
- `yarn install --immutable` *(fails: tunneling socket could not be established)*
- `yarn test` *(fails: project doesn't seem to have been installed)*
> fix: unsubscribe handling in EventEmitter

- sdk/js/__tests__/EventEmitter.spec.js
- fix typos in `sdk/js/__tests__/EventEmitter.spec.js`
- `yarn test` *(fails: project dependencies not installed)*
> fix: misspelling in EventEmitter tests

- .github/workflows/run-test-harness.yml
- scripts/lerna-version-ci.sh
- scripts/lerna-version.sh
This PR fixes GitHub Action failures by replacing deprecated nx print-affected commands with nx show projects --affected syntax. Updated scripts/lerna-version-ci.sh and scripts/lerna-version.sh to use modern Nx 21.1.1 compatible commands.
> fix: replace deprecated nx print-affected commands

- scripts/lerna-version-ci.sh
> fix: ignore devcycle-js-sdks package in lerna-version script

- lib/shared/bucketing-assembly-script/__tests__/bucketing/bucketing.test.ts
- lib/shared/bucketing-assembly-script/assembly/types/target.ts
- lib/shared/bucketing-assembly-script/assembly/types/targetV2.ts
- lib/shared/bucketing/__tests__/bucketing.test.ts
- lib/shared/bucketing/src/bucketing.ts
- add checking for rare case when the bounded hash is 1 
- add test for the bucketing libs
> fix: handle the bounded hash limit for edge cases

- sdk/js/__tests__/Client.spec.js
- sdk/js/__tests__/User.spec.js
- sdk/js/src/Client.ts
- sdk/js/src/User.ts
- sdk/openfeature-angular-provider/__tests__/DevCycleAngularProvider.test.ts
- sdk/openfeature-react-provider/__tests__/DevCycleReactProvider.test.ts
- sdk/openfeature-web-provider/__tests__/DevCycleProvider.test.ts
- sdk/openfeature-web-provider/src/DevCycleProvider.ts
This pull request introduces significant updates to the handling of anonymous users, alongside improvements to test coverage and error messaging. The most important changes include refining the logic for anonymous and non-anonymous user creation, updating test cases to reflect the new behavior, updating the OpenFeature Web Provider to handle anon Contexts, and enhancing the flexibility of user ID resolution in various contexts.
* [`sdk/js/src/User.ts`](diffhunk://#diff-c043fbefa1714bfa4e7dc2c288591e7c668c1db171aa82a454c2b2eef00aaa97R39-R87): Enhanced the `DVCPopulatedUser` class to handle cases where `user_id` is an empty string or missing. Introduced a `generateAndSaveAnonUserId` method to create and optionally store anonymous user IDs. Improved validation to ensure `isAnonymous: false` …
> fix: DVCPopulatedUser user_id and isAnonymous handling to be consistent with other SDKs

- lib/shared/bucketing/__tests__/bucketing.test.ts
- lib/shared/bucketing/src/bucketing.ts
- lib/shared/types/src/types/apis/sdk/clientSDKAPI.ts
- sdk/js-cloud-server/__tests__/cloudClient.spec.ts
- sdk/js-cloud-server/src/__mocks__/handlers.ts
- fix: adds `Random Distribution` or `Rollout` to eval reason details to better identify the evaluation reason of `SPLIT` 
- chore: adds new attribute of `target_id` to eval reason
- chore: updates test expectations for Random Distributions & Rollouts to include the proper evaluation reasons
> fix: add split details to js bucketing

- sdk/js-cloud-server/__tests__/cloudClient.spec.ts
- sdk/js-cloud-server/__tests__/evalHooksRunner.test.ts
- sdk/js-cloud-server/src/cloudClient.ts
- sdk/js-cloud-server/src/hooks/EvalHook.ts
- sdk/js-cloud-server/src/hooks/EvalHooksRunner.ts
- sdk/js-cloud-server/src/hooks/HookContext.ts
- sdk/js-cloud-server/src/index.ts
- sdk/nodejs/__tests__/initialize.spec.ts
- added eval hooks to js cloud server and nodejs cloud client
> feat: added hooks to js cloud server

- sdk/js-cloud-server/__tests__/cloudClient.spec.ts
- sdk/js-cloud-server/src/cloudClient.ts
- sdk/js-cloud-server/src/index.ts
- sdk/js/__tests__/Client.test.ts
- sdk/js/src/Client.ts
- sdk/js/src/hooks/EvalHooksRunner.ts
- sdk/js/src/types.ts
- added hooks to options to initialize clients with
> feat: added hooks to options to initialize clients with hooks

- sdk/nestjs/src/RequireVariableValue.ts
- sdk/nestjs/src/VariableValue.ts
- changed variable decorators to use variable definitions so that there's more strict typing on the variable keys if the user chooses to define them
> feat: added variable definition typing for decorators in nestjs sdk

- sdk/js-cloud-server/package.json
- sdk/js/package.json
- sdk/nestjs/package.json
- sdk/nextjs/package.json
- sdk/nodejs/package.json
- sdk/openfeature-angular-provider/package.json
- sdk/openfeature-nestjs-provider/package.json
- sdk/openfeature-react-provider/package.json
- sdk/openfeature-web-provider/package.json
- sdk/react-native-expo/package.json
- sdk/react-native/package.json
- sdk/react/package.json
- yarn.lock
This change updates all SDK packages to use tilde (`~`) version ranges instead of caret (`^`) for internal `@devcycle` and `@openfeature` dependencies, restricting updates to patch versions only.
- Updated 12 SDK package.json files across `sdk/` directory
- Changed dependency version ranges from `^` to `~` for all `@devcycle/*` packages
- Changed dependency version ranges from `^` to `~` for `@openfeature/*` packages  
- Preserved `^` ranges for `peerDependencies` and third-party packages
- **Before**: `"@devcycle/types": "^1.30.0"` (allows minor + patch updates)
- **After**: `"@devcycle/types": "~1.30.0"` (allows patch updates only)
This ensures more predictable dependency resolution and reduces the risk of breaking changes from minor version updates in internal packages.
> fix: tighten package.json dependancies for @devcycle / @openfeature to patch versions

- sdk/nodejs/__tests__/open-feature-provider/DevCycleProvider.test.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/index.ts
- sdk/nodejs/src/open-feature/DevCycleProvider.ts
- SDK platform not properly identified for OpenFeature integration
- Deprecated `getOpenFeatureProvider()` method lacked clear guidance
- OpenFeature provider tests failing due to improper client instantiation and mock bleeding
- **Platform**: Set `sdkPlatform` to `'nodejs-of'` for proper tracking
- **Deprecation**: Added warnings to `getOpenFeatureProvider()` methods with migration docs
- **Tests**: Fixed client type instantiation and added proper mock cleanup with `afterEach`
```typescript
// Before (deprecated)
const client = new DevCycleClient(sdkKey, options)
const provider = await client.getOpenFeatureProvider()
// After
const provider = new DevCycleProvider(sdkKey, options)
// For cloud: new DevCycleProvider(sdkKey, { ...options, enableCloudBucketing: true })
```
> fix: setting OpenFeature Provider sdkPlatform, update tests, mark getOpenFeatureProvider() as deprecated

- .gitignore
- .yarnrc.yml
- sdk/js/src/Client.ts
- sdk/js/src/Variable.ts
- sdk/nodejs/src/pb-types/pbTypeHelpers.ts
- sdk/openfeature-angular-provider/__tests__/DevCycleAngularProvider.test.ts
- sdk/openfeature-react-provider/__tests__/DevCycleReactProvider.test.ts
- sdk/openfeature-web-provider/__tests__/DevCycleProvider.test.ts
- add _feature property to protobuf version and also to the DVC variable  
benchmark changes
> feat: add _feature to the evaluated variable

- lib/shared/bucketing-assembly-script/assembly/types/configBody.ts
- sdk/nodejs/src/client.ts
- instead of stringifying the object, adding the project and environment to be objects and stringifying the parent object
- tested locally using devapp
> fix: update config metadata to stringify properly

- sdk/js-cloud-server/src/models/variable.ts
- sdk/nodejs/__tests__/evalHooksRunner.test.ts
- sdk/nodejs/src/client.ts
- sdk/nodejs/src/hooks/EvalHook.ts
- sdk/nodejs/src/hooks/EvalHooksRunner.ts
featureId is needed in hooks for dynatrace integration to construct feature url. 
Created a VariableMetadata class to provide the data to the hook wrapper while maintaining the original public variable functions signature.
> feat: provide featureId to hooks
